In [1]:
# numeric python

import numpy as np


In [ ]:
#multi dimentional
#single dimentional

#np.array

a=[1,2,3,4]     # while working with numpy both variable list should have same length of rows and columns
b=[5,6,7,8]

c=a+b
print(c)



[1, 2, 3, 4, 5, 6, 7, 8]


In [3]:
arr_a=np.array(a)
arr_b=np.array(b)

In [4]:
type(a)

list

In [ ]:
type(arr_a)     

numpy.ndarray

In [7]:
arr_c= arr_a+arr_b
arr_c

array([ 6,  8, 10, 12])

multidimentional array

In [10]:
multi_arr=(
    [1,2,3,4],
    [4,5,6,7],
    [8,9,10,11]

)

In [12]:
a=np.array(multi_arr)

print(a)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
#U --> unicode
#string array

data= np.array(['Nepal','UK','Bhutan'])
data                                             #dtype='U6' represnts the largest alphabetical count

array(['Nepal', 'UK', 'Bhutan'], dtype='<U6')

Zero and Ones

In [19]:
#zeros/ ones(shape,dtype =default(float)/int)

zeros_1d= np.zeros(5,dtype=int)
zeros_1d

array([0, 0, 0, 0, 0])

In [16]:
zeros_2d= np.zeros((5,6),dtype=int)
zeros_2d

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [17]:
ones_1d= np.ones(5,dtype=int)
ones_1d

array([1, 1, 1, 1, 1])

Arange

In [22]:
#arange (start,stop,step)

num=np.arange(0,20,2)
num


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#this whole thing can be done using Arange()

num=[]
for i in range(0,20,2):
    num.append(i)
n=np.array(num)
print(n)

[ 0  2  4  6  8 10 12 14 16 18]


Reshape and ravel

In [ ]:
''' 
Reshape == change dimention of an array
Ravel // flatten==  change any dimention array to one dimention array


'''

In [25]:
n.shape

(10,)

In [26]:
reshape_numbers=n.reshape(2,5)
reshape_numbers

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [ ]:
ravel_numbers=np.ravel(reshape_numbers)     #converting back to one dimentional
ravel_numbers

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Slicing

In [33]:
num=np.arange(0,60)
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [30]:
num[3:14]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
reshape_numbers=num.reshape(5,12)
reshape_numbers

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [36]:
# arrray[row,column]

reshape_numbers[1:3,4:5]

array([[16],
       [28]])

Array Broadcasting

In [ ]:
''' 
Rules of Array Braodcasting
1. all shape and size of arrays must be equal
2, one shape should be one and other must be equal 

or ther should i 1*1 array which would work

'''

In [39]:
arr=np.array([
    [1,2,3],
    [4,5,6],
    [6,7,8]
])

data=np.array([ 
    [6,4,3],
    [2,3,1],
    [3,4,2]
])

add= arr+data
print(add)

[[ 7  6  6]
 [ 6  8  7]
 [ 9 11 10]]


Boolean Indexing

In [40]:
# used fo data filtering

num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [41]:
num > 45

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [ ]:
filt_num=num>45
num[filt_num]

#num[num>45]

array([46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [47]:
data= np.array(['Nepal','UK','Bhutan','UK'])
data[data=='UK']

array(['UK', 'UK'], dtype='<U6')